---
title: System Structure and Parametrization
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: contact@ssp-standard.org
description: 'System Structure and Parameterization (SSP) is a tool independent standard to define complete systems consisting of one or more FMUs including its parameterization that can be transferred between simulation tools.'
url: http://ssp-standard.org
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
